### ISSUE TITLE
如何获取context

### ISSUE THREAD

**Issue by 25juan** [eggjs/tegg#106]
### 如何在类属性上获取当前访问context上下文实例

想要在BaseController上注入context属性。封装统一的返回结构。
但是貌似像我下面的写法没调用context.body进行返回数据给前端

![image](https://user-images.githubusercontent.com/14308183/223423071-32d7220c-1d4d-4459-bc50-f3f66c7c6091.png)

### 可复现问题的仓库地址（Reproduction Repo）

暂无地址

### Node 版本号：

v16.19.1

### TEgg 版本号：

3.5.2

### 相关插件名称与版本号：

无

### 操作平台与版本号：

windows10

**Comment by 25juan** [comment]
还是用注解注入吧 貌似没找到方法

**Comment by MineFurjiko** [comment]
你的编辑器 主题和字体是什么呀？

**Comment by Foveluy** [comment]
`
import { EggLogger } from "egg";
import {
  Inject,
  HTTPController,
  HTTPMethod,
  HTTPMethodEnum,
  EggContext,
  ContextProto,
} from "@eggjs/tegg";

@HTTPController({
  path: "/",
})
@ContextProto()
export class HomeController {
  @Inject()
  logger: EggLogger;

  @Inject()
  public context: EggContext;

  @HTTPMethod({
    method: HTTPMethodEnum.GET,
    path: "/",
  })
  async index() {
    this.logger.info("hello egg logger");
    return "hello egg";
  }

  @HTTPMethod({
    method: HTTPMethodEnum.POST,
    path: "/upload-map-data",
  })
  async first() {
    this.logger.info("hello egg logger");
    this.logger.info("hello egg logger", Object.keys(this.context.request));

    // console.log(this.)

    return "hello egg";
  }
}
`
按照你的代码写了个测试，发现怎么都获取不到 request上的东西，requestbody也没有。

使用的是`curl http://localhost:7001/upload-map-data -X 'POST' -d '{"foo":"bar"}' -H 'Content-Type: application/json'`

**Comment by killagu** [comment]
参考这里 https://github.com/eggjs/tegg/tree/master/plugin/controller#context

context 不支持注入。

```typescript
// app/controller/FooController.ts
import { Context, EggContext } from '@eggjs/tegg';

export class FooController {
  @Middleware(methodCount)
  async hello(@Context() ctx: EggContext) {
  }
}
```
