### ISSUE TITLE
请问中间件怎么调用service

### ISSUE THREAD

**Issue by Mjh1231** [eggjs/tegg#109]
### 在此输入你需要反馈的 Bug 具体信息（Bug in Detail）：

![image](https://user-images.githubusercontent.com/37246223/225186135-28fd1ae1-0bed-471f-a56e-9b2a540cb858.png)

![image](https://user-images.githubusercontent.com/37246223/225250814-90223148-1c70-4f19-965c-94e2d3531e7e.png)

在中间件调用service 但是一直undefined，有没有什么方法注入到中间件里面

### 可复现问题的仓库地址（Reproduction Repo）

暂无

### Node 版本号：

v14.17.0

### TEgg 版本号：

3.5.2

### 相关插件名称与版本号：

egg:3.15.0 ，  egg-bin:5.13.4

### 操作平台与版本号：

win10

**Comment by lmovse** [comment]
Service 不是挂在 ctx.service 下面, 使用 ctx.app.getEggObject 获取

```typescript
const cacheService = await ctx.app.getEggObject(CacheService);
```

**Comment by Mjh1231** [comment]
> Service不是挂在ctx.service下面，使用ctx.app.getEggObject获取
> 
> ```ts
> const cacheService = await ctx.app.getEggObject(CacheService);
> ```

学到了 谢谢大佬！
