### ISSUE TITLE
tegg-orm-decorator 和 sequelize怎么一起使用

### ISSUE THREAD

**Issue by 25juan** [eggjs/tegg#110]
### 在此输入你需要反馈的 Bug 具体信息（Bug in Detail）：

tegg-orm-decorator 和 sequelize怎么一起使用

### 可复现问题的仓库地址（Reproduction Repo）

tegg-orm-decorator 和 sequelize怎么一起使用

### Node 版本号：

v14.18.1

### TEgg 版本号：

v3.5.2

### 相关插件名称与版本号：

3.6.3

### 操作平台与版本号：

windows10

**Comment by killagu** [comment]
现在不支持 sequelize。只支持 leoric。

**Comment by snail-boy** [comment]
官方什么时间支持sequlize
