### ISSUE TITLE
beginModuleScope获取不到

### ISSUE THREAD

**Issue by AnizGu** [eggjs/tegg#111]
![image](https://user-images.githubusercontent.com/69628287/227914598-3467fe80-ac65-44d5-abf9-7fa002910b9c.png)
根据这个例子获取service，但是module里是{}空对象

**Comment by killagu** [comment]
https://github.com/eggjs/tegg/tree/master/core/schedule-decorator schedule 注解已经实现了。

如果需要排查一下 begineModuleScope 的问题，麻烦提供一个可重现的例子。

**Comment by killagu** [comment]
欢迎随时再打开 issue。
