### ISSUE TITLE
【addSingleton 注册插件报的一个错】：当注册 async function时，function内使用await报错

### ISSUE THREAD

**Issue by yinshanhu** [eggjs/tegg#115]
### 在此输入你需要反馈的 Bug 具体信息（Bug in Detail）：

我这边的使用场景是：
redis地址需要动态获取，因此需要请求接口获取配置，于是自定义redis插件，初始化之前发起异步请求。

_egg-redis的配置，我在demo上是瞎写的，不过不用关心，报此类错误可以忽略，关键是加了await后还走不到这一步。_

**演示步骤如下：**
**1.下方的demo仓库，我是稍微改造了官方的eggjs-redis插件：**
改动点在： app/plugins/egg-redis/lib/redis.js
![image](https://user-images.githubusercontent.com/47800953/231932121-ab5a51f4-4121-4c3a-aee5-04a76717e17c.png)
**2.插件配置如下（通过path指向插件）：**
![image](https://user-images.githubusercontent.com/47800953/231932242-c69c339e-6e71-44f5-be4b-54717f478779.png)
3.Service层注入redis插件如下：
![image](https://user-images.githubusercontent.com/47800953/231932368-e28b4fa0-d691-4c54-bf34-9d4ce858318c.png)

**4.加了await后，npm run dev，报错如下：**
 ERROR 73152 framework.EggPrototypeNotFound: Object redis not found in LOAD_UNIT:foo [ https://eggjs.org/zh-cn/faq/TEGG_EGG_PROTO_NOT_FOUND ]
......................................................................
......................................................................
......................................................................
code: TEGG_EGG_PROTO_NOT_FOUND
serialNumber: EGG_PROTO_NOT_FOUND
errorContext: ""

**奇怪：**
1、加await处的代码报错捕获不到，感觉一加await就像跳过了当前的执行。
2、axios、app.curl试了都不行。
3、只要去掉await，非同步执行都ok。

麻烦大佬们帮看看，非常感谢~~

### 可复现问题的仓库地址（Reproduction Repo）

https://github.com/yinshanhu/eggjs-addSingleton-asyncFunction-error.git

### Node 版本号：

v18.12.1

### TEgg 版本号：

3.5.2

### 相关插件名称与版本号：

无

### 操作平台与版本号：

window11

**Comment by fengmk2** [comment]
@yinshanhu 感谢反馈，我们会排查一下。

**Comment by yinshanhu** [comment]
> @yinshanhu 感谢反馈，我们会排查一下。

有进度吗？哈哈

**Comment by fengmk2** [comment]
https://github.com/eggjs/egg-redis/blob/master/lib/redis.js#L11 addSingleton 只支持同步函数，不支持 async function 的。
redis 插件没有注册成功，你自定义插件的问题，使用 egg-redis 插件是可以启动的。

**Comment by yinshanhu** [comment]
> https://github.com/eggjs/egg-redis/blob/master/lib/redis.js#L11 addSingleton 只支持同步函数，不支持 async function 的。 redis 插件没有注册成功，你自定义插件的问题，使用 egg-redis 插件是可以启动的。

**好的，感谢。我是看文档上说已经支持async function。**
![image](https://user-images.githubusercontent.com/47800953/232654736-b7efe964-22fc-477e-9824-a70132615c99.png)

**还想请教个问题：**
对于我这种需要自定义异步插件的场景，有没有别的解决方案？

**Comment by killagu** [comment]
现在只能扫描到 extends 上有的，可以通过 addSingleton 来添加到 _redis，然后在 extends 里添加 redis 来做代理。
