### ISSUE TITLE
egg-redis

### ISSUE THREAD

**Issue by z2244713679** [eggjs/tegg#116]
### 哈喽，我想咨询一下在 `tegg` 里面如何使用 `egg-redis` 中间件
我使用这种方式可以 `log` 出值 `redies.get('foo')` 的值
但是会有两个问题
1. 使用 `ctx.app.redis` ts 会提示 类型“Application”上不存在属性“redis”
2. 使用这种方式接口请求会报404 ，也没有走到 ERR

还想咨询一下，除过readme 还有其他的tegg的文档吗

### index.ts
```
async index(@Context() ctx: EggContext) {
    try {
      // @ts-ignore
      const data = await ctx.app.redis.get('foo');
      console.log(data);
      return 'hello word';
    } catch (err) {
      console.log(err);
      return 'hello word error';
    }
  }
```

### config.default.ts
```
  config.redis = {
    client: {
      port: 6379, // Redis port
      host: '127.0.0.1', // Redis host
      password: 'my_react_admin_app',
      db: 0,
    },
  };
```
### plugin.ts
```
 redis: {
    enable: true,
    package: 'egg-redis',
  },
```

**Comment by WuWhite** [comment]
redis需要注入    
// 明确指定注入 app 上的 redis 不是 ctx上的
  @EggQualifier(EggType.APP)
  redis: any;

然后在function里面就可以this.redis使用了
