### ISSUE TITLE
配置项目 module 使用 `pkg` 报错，与README文档不符，这里是否只支持`package`?

### ISSUE THREAD

**Issue by nxps** [eggjs/tegg#117]
### 在此输入你需要反馈的 Bug 具体信息（Bug in Detail）：

使用 `pkg` 直接报错

```bash
ERROR 27855 nodejs.Error: unknown type of module reference config: {"pkg":"cnpmcore/common"}
    at Function.readModuleReferenceFromModuleJson (/Users/xxx/github/hello-tegg/node_modules/@eggjs/tegg-common-util/src/ModuleConfig.ts:85:15)
    at Function.readModuleReference (/Users/xxx/github/hello-tegg/node_modules/@eggjs/tegg-common-util/src/ModuleConfig.ts:62:19)
```
README 文档:

![image](https://github.com/eggjs/tegg/assets/17310314/85f427f9-af17-48e9-a6bb-63df4286ce39)

### 可复现问题的仓库地址（Reproduction Repo）

测试的是
https://github.com/eggjs/examples/blob/bed580fe053ae573f8b63f6788002ff9c6e7a142/hello-tegg/config/module.json

### Node 版本号：

v18.16.0

### TEgg 版本号：

3.7.0

### 相关插件名称与版本号：

cnpmcore, 3.20.2 

### 操作平台与版本号：

macOS 13.3.1 (22E261)

**Comment by killagu** [comment]
是 `package` 不是 `pkg`

**Comment by killagu** [comment]
https://github.com/eggjs/tegg/blob/master/core/common-util/src/ModuleConfig.ts#L28

**Comment by killagu** [comment]
欢迎来个 readme 提个 PR 修正下。
