### ISSUE TITLE
[Feature Request] 使用 egg-typebox-validate 作为默认的参数校验插件

### ISSUE THREAD

**Issue by fengmk2** [eggjs/tegg#16]
是否可以引入 https://github.com/xiekw2010/egg-typebox-validate 成为默认的 validate 插件，之前的 egg-validate 在 ts 下其实不太满足。

cc @xiekw2010

**Comment by fengmk2** [comment]
@atian25 @killagu @whxaxes 怎么看？

**Comment by fengmk2** [comment]
示例 https://github.com/cnpm/cnpmcore/pull/12

**Comment by xiekw2010** [comment]
![image](https://user-images.githubusercontent.com/1814071/144557184-583f8255-c43d-474a-b973-975c3e7201e6.png)

可以考虑把 validate 直接作为一个装饰器，controller 里面专注业务代码，更干净了

**Comment by killagu** [comment]
这个加在入参上比较好，比如说同时有 query，params 的，每个参数都可以有教研。

**Comment by popomore** [comment]
参数定义和校验一体化（包括lei）会比较好一点。

除了基础类型还有业务校验，这个根据 @xiekw2010 说的写法会比较好一些，不要侵入函数本身。

**Comment by fengmk2** [comment]
@xiekw2010 继续推进？
