### ISSUE TITLE
如何注入类本身使用他的静态方法的

### ISSUE THREAD

**Issue by js571** [eggjs/tegg#181]
### 在此输入你需要反馈的 Bug 具体信息（Bug in Detail）：

1. 我参考cnpmcore那边代码写的，想要注入后使用类的静态方法
2. 实际使用时候没有办法获取到注入对象的静态方法

想想可以直接import进来直接用，但是我看cnpmcore里可以导入 @Model() 注解下的导入，我自己按下面代码测试就注入后对象的方法

controller代码如下：
```
import { Inject, HTTPController, HTTPMethod, HTTPMethodEnum } from '@eggjs/tegg';
import type { UserService } from '../service/UserService';

@HTTPController({
  path: '/',
})
export class HomeController {
  @Inject()
  private readonly userService: typeof UserService;

  @HTTPMethod({
    method: HTTPMethodEnum.GET,
    path: '/',
  })
  async index() {
    this.userService.find();
    return 'hello egg';
  }
}
```

service代码如下:
```
import { AccessLevel, SingletonProto } from '@eggjs/tegg';

@SingletonProto({
  accessLevel: AccessLevel.PUBLIC
})
export class UserService {
  static find() {
    console.log('find');
  }
}
```

### 可复现问题的仓库地址（Reproduction Repo）

[tegg_learn.zip](https://github.com/eggjs/tegg/files/13790902/tegg_learn.zip)

### Node 版本号：

16.17.0

### TEgg 版本号：

^3.5.2

### 相关插件名称与版本号：

 "@eggjs/tegg-aop-plugin": "^3.5.2",

### 操作平台与版本号：

macOs 14.2 (23C64)

**Comment by popomore** [comment]
不建议用静态方法，SingletonProto 在生命周期只会实例化一次，类似静态方法了。静态方法可以直接 import 使用？

**Comment by js571** [comment]
> 不建议用静态方法，SingletonProto 在生命周期只会实例化一次，类似静态方法了。静态方法可以直接 import 使用？

import意思是当一个普通的类，比如下面
```
export default class  Utils {
 static find() {...}
}

import Utils from ''
Utils.find()


```

**Comment by popomore** [comment]
是的，正常使用就好了。或者按我说的，使用 Singleton 并定义实例方法。
