### ISSUE TITLE
framework.EggPrototypeNotFound: Object searchAdapter not found in LOAD_UNIT:cnpmcoreRepository 有什么降级方案吗

### ISSUE THREAD

**Issue by nxps** [eggjs/tegg#183]
### 在此输入你需要反馈的 Bug 具体信息（Bug in Detail）：

使用 cnpmcore + tegg 开发，cnpmcore v3.38.2, tegg v3.12.0 版本，原本没有问题，升级到 v3.29.0 后启动报错 `framework.EggPrototypeNotFound: Object searchAdapter not found in LOAD_UNIT:cnpmcoreRepository`;

锁版本 tegg 相关包锁在 3.12.0，cnpmcore v3.38.2，报错 `nodejs.ERR_PACKAGE_PATH_NOT_EXPORTEDError: [egg-core] load file: /Users/xxx/demo/node_modules/@eggjs/tegg-orm-plugin/app.js, error: Package subpath './src/setup_hooks' is not defined by "exports" in /Users/xxx/demo/node_modules/leoric/package.json`；

查看 cnpmcore 依赖后，发现 "@eggjs/tegg": "^3.12.0"，所以会安装依赖 3.12.0 3.29.0，这两个版本不兼容吗？

### 可复现问题的仓库地址（Reproduction Repo）

无

### Node 版本号：

18.19.0

### TEgg 版本号：

3.29.0

### 相关插件名称与版本号：

cnpmcore, 3.38.2

### 操作平台与版本号：

macOS 13.5.2 (22G91)

**Comment by fengmk2** [comment]
这是 cnpmcore 的问题，这里就关闭了
